print(list('hello'))
x=[1,1,1]
x[1]=2
print(x)
names=['Alice','Beth','Cecil','Dee-Dee','Earl']
del names[2]
print(names)
name=list('Perl')
name[2:]=list('ar')
print(name)
numbers=[1,2,3,4,5]
numbers[1:4]=[]
print(numbers)
numbers.append(6)
print(numbers)
numbers.clear()
print(numbers)
a=[1,2,3]
b=a
b[1]=4
print(a)
print(b) #常规复制仅将另一名称关联到列表，指向不同列表需将b关联到a的副本
c=[1,2,3]
d=c.copy()
d[1]=4
print(c)
print(d)
x=['to','be','or','not','to','be']
x.remove('be')#删除为指定值的第一个元素
print(x)
d.reverse()
print(d)
y=[4,6,7,2,3,1,7,9,8]
z=sorted(y)
y.sort()
print(y)
print(z)
p=['aardvark','abalone','acme','add','aerate']
p.sort(key=len)
print(p)
